# Generated by Django 6.0.7 on 2026-07-28 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0028_add_service_description"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        max_length=200,
                        unique=True,
                        verbose_name="اسلاگ",
                    ),
                ),
                ("summary", models.TextField(blank=True, verbose_name="خلاصه")),
                ("body", models.TextField(verbose_name="متن")),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="blog/", verbose_name="تصویر"
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True, max_length=500, verbose_name="لینک تصویر (جایگزین)"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="منتشر شده"
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاریخ انتشار"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="آخرین به\u200cروزرسانی"
                    ),
                ),
            ],
            options={
                "verbose_name": "پست وبلاگ",
                "verbose_name_plural": "پست\u200cهای وبلاگ",
                "ordering": ["-published_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BlogPostRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.PositiveSmallIntegerField(verbose_name="امتیاز (۱ تا ۵)"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین ویرایش"),
                ),
            ],
            options={
                "verbose_name": "امتیاز پست وبلاگ",
                "verbose_name_plural": "امتیازهای پست\u200cهای وبلاگ",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="comment",
            name="comment_has_target",
        ),
        migrations.AddField(
            model_name="blogpost",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blog_posts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="نویسنده",
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="blog_post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="comments",
                to="services.blogpost",
                verbose_name="پست وبلاگ",
            ),
        ),
        migrations.AddConstraint(
            model_name="comment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("service__isnull", False),
                    ("service_center__isnull", False),
                    ("blog_post__isnull", False),
                    _connector="OR",
                ),
                name="comment_has_target",
            ),
        ),
        migrations.AddField(
            model_name="blogpostrating",
            name="blog_post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ratings",
                to="services.blogpost",
                verbose_name="پست وبلاگ",
            ),
        ),
        migrations.AddField(
            model_name="blogpostrating",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blog_ratings",
                to=settings.AUTH_USER_MODEL,
                verbose_name="کاربر",
            ),
        ),
        migrations.AddConstraint(
            model_name="blogpostrating",
            constraint=models.CheckConstraint(
                condition=models.Q(("score__gte", 1), ("score__lte", 5)),
                name="blog_rating_score_range",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="blogpostrating",
            unique_together={("user", "blog_post")},
        ),
    ]
