# Generated by Django 6.0.7 on 2026-07-28 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0029_blogpost_blogpostrating_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="keywords",
            field=models.TextField(blank=True, verbose_name="کلمات کلیدی"),
        ),
    ]
