# Generated by Django 6.0.7 on 2026-07-29 06:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0030_blogpost_keywords"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="view_count",
            field=models.PositiveIntegerField(default=0, verbose_name="تعداد بازدید"),
        ),
    ]
