# Generated by Django 6.0.7 on 2026-07-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0031_blogpost_view_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="alt_text",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="متن جایگزین تصویر"
            ),
        ),
    ]
