# Generated by Django 6.0.7 on 2026-07-30 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0032_blogpost_alt_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="bio",
            field=models.TextField(blank=True, verbose_name="بیوگرافی"),
        ),
    ]
