# Generated by Django 6.0.7 on 2026-07-30 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0033_userprofile_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="blog_post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="services.blogpost",
                verbose_name="پست وبلاگ",
            ),
        ),
    ]
