# Generated by Django 6.0.7 on 2026-08-07 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0034_alter_comment_blog_post_on_delete_cascade"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="bookmark",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="bookmark",
            name="service_center",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookmarks",
                to="services.servicecenter",
            ),
        ),
        migrations.AlterField(
            model_name="bookmark",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookmarks",
                to="services.service",
            ),
        ),
        migrations.AddConstraint(
            model_name="bookmark",
            constraint=models.UniqueConstraint(
                condition=models.Q(("service__isnull", False)),
                fields=("user", "service"),
                name="unique_bookmark_user_service",
            ),
        ),
        migrations.AddConstraint(
            model_name="bookmark",
            constraint=models.UniqueConstraint(
                condition=models.Q(("service_center__isnull", False)),
                fields=("user", "service_center"),
                name="unique_bookmark_user_service_center",
            ),
        ),
    ]
