# Generated by Django 6.1 on 2026-08-09 05:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0035_alter_bookmark_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="bookmark",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("service__isnull", False), ("service_center__isnull", True)
                    ),
                    models.Q(
                        ("service__isnull", True), ("service_center__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="bookmark_exactly_one_target",
            ),
        ),
    ]
