# Generated by Django 6.1 on 2026-08-10 08:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0037_themepreference"),
    ]

    operations = [
        migrations.AddField(
            model_name="faq",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                default=django.utils.timezone.now,
                verbose_name="آخرین ویرایش",
            ),
            preserve_default=False,
        ),
    ]
