# Generated by Django 6.1 on 2026-08-10 09:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0038_faq_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteContactInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="ایمیل"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=30, verbose_name="تلفن"),
                ),
            ],
            options={
                "verbose_name": "اطلاعات تماس سایت",
                "verbose_name_plural": "اطلاعات تماس سایت",
            },
        ),
    ]
